inherit_from: .rubocop_todo.yml
HasAndBelongsToMany:
  Enabled: false
AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
